---
title: "Probability - Demo"
author: "Becky Tang"
date: "9/30/2022"
output: html_document
---

```{r packages, include = F}
library(tidyverse)
```

```{r setup, echo = F}
coffee <- c(rep("Does not drink coffee", 6477), rep("Drinks coffee occasionally", 34152), rep("Drinks coffee regularly", 28535))
died <- c(rep("Died", 1039), rep("Did not die", 5438), 
          rep("Died", 4440), rep("Did not die", 29712),
          rep("Died", 3601), rep("Did not die", 24934))
coffee_data = tibble(coffee_use = coffee,
                     status = died)
knitr::kable(table(coffee_use = coffee_data$coffee_use, status = coffee_data$status))
```

Number of people in our dataset:

```{r}
```


Let event A = died and event B = non-coffee drinker. Calculate the following for a randomly selected person in the cohort

a) P(died)

```{r prob_A}

```

```{r prob_A_ans, echo = F, eval = F}
# P(A) = P(died)
coffee_data %>%
  count(died) %>%
  mutate(proportion = n / sum(n))

```


b) P(non-coffee drinker)

```{r prob_B}

```

```{r prob_B_ans, echo = F, eval = F}
# P(B) = P(non coffee)
coffee_data %>%
  count(coffee) %>%
  mutate(proportion = n / sum(n))

```

c) P(died and non-coffee drinker)

```{r prob_AB}

```

```{r prob_AB_ans, echo = F, eval = F}
# P(A and B) = P(died and non-coffee)
coffee_data %>%
  filter(died == "Died",
         coffee == "Does not drink coffee") %>%
  nrow()

coffee_data %>%
  count(died, coffee) %>%
  mutate(proportion = n / sum(n))
```


d) P(died or non-coffee drinker)

```{r prob_AoB}

```

```{r prob_AoB_ans, echo = F, eval = F}
# P(A or B) = P(A) + P(B) - P(A and B) 
p_a <- 0.131
p_b <- 0.094
p_aob <- 0.015

p_a + p_b - p_aob
```

e) P(died or coffee drinker)

```{r prob_AoBc}

```

```{r prob_AoBc_ans, echo = F, eval = F}
# P(A or Bc)
p_a + (1 - p_b) - (0.064 + 0.052)
```



